// Generated by LiveScript 1.4.0
(function(){
  var $, jquery, projectName, util, ref$, log, ierror, isNum, isInt, isANum, round, $main, items, numItems, $container, containerWidth, containerHeight, spanWidths, longestWidth, spanHeightLarge;
  $ = jquery = require('./lib/jquery');
  projectName = 'fish-headings';
  ref$ = util = require('./util'), log = ref$.log, ierror = ref$.ierror, isNum = ref$.isNum, isInt = ref$.isInt, isANum = ref$.isANum, round = ref$.round;
  module.exports = {
    init: init
  };
  $main = void 8;
  items = [];
  numItems = -1;
  $container = void 8;
  containerWidth = -1;
  containerHeight = -1;
  spanWidths = [];
  longestWidth = -1;
  spanHeightLarge = void 8;
  function init($_container, vals){
    var x$, $main;
    $container = $_container;
    containerWidth = $container.width();
    numItems = vals.length;
    x$ = $main = $('<div>');
    x$.attr('id', projectName);
    vals.forEach(function(v, i){
      var inner, x$, $item, y$, $span;
      inner = v;
      x$ = $item = $('<div>');
      x$.attr('id', i);
      y$ = $span = $('<span>');
      y$.html(inner);
      $main.append($item);
      $item.append($span);
      return items.push($item);
    });
    $container.append($main);
    return containerHeight = $container.height();
  }
  function collapse(n){
    var tops, lefts;
    tops = [];
    lefts = [];
    items.forEach(function($v){
      var offset, $span, width;
      offset = $v.position();
      tops.push(offset.top);
      lefts.push(offset.left);
      $span = $v.find('span');
      width = $span.width();
      longestWidth = Math.max(width, longestWidth);
      if (spanHeightLarge == null) {
        spanHeightLarge = $span.height();
      }
      spanWidths.push(width);
      log('pushing width', $span.width());
      return log('pushing left', offset.left);
    });
    items.forEach(function($v){
      var top, left;
      top = tops.shift();
      left = lefts.shift();
      return $v.css('position', 'absolute').css('top', top).css('left', left);
    });
    return setTimeout(function(){
      return select(n);
    }, 0);
  }
  function select(n){
    var widthEnabled, j;
    widthEnabled = -1;
    items.forEach(function($v, i){
      $v.removeClass('disabled').removeClass('enabled');
      if (i === n) {
        return $v.addClass('enabled');
      } else {
        return $v.addClass('disabled');
      }
    });
    log('container-height', containerHeight);
    log('span-height-large', spanHeightLarge);
    j = -1;
    return items.forEach(function($v, i){
      var top, spanHeightSmall;
      if (i === n) {
        $v.css('left', 0);
        top = containerHeight / 2 - spanHeightLarge / 2;
        return $v.css('top', top);
      } else {
        j++;
        $v.css('left', longestWidth + 15);
        spanHeightSmall = 10;
        top = (containerHeight - spanHeightSmall) / (numItems - 2) * j;
        return $v.css('top', top);
      }
    });
  }
  function collapse2(n){
    var widthLast, leftFirst, leftLast, availableWidth, spacing;
    widthLast = spanWidths[numItems - 1];
    leftFirst = 0;
    log('width-last', widthLast);
    leftLast = containerWidth - widthLast;
    log('container-width', containerWidth);
    log('left-last', leftLast);
    availableWidth = leftLast - leftFirst;
    spacing = availableWidth / numItems;
    return items.forEach(function($v, i){
      var left;
      return;
      left = leftFirst + spacing * i;
      return $v.css('top', 0).css('left', left);
    });
  }
  window.collapse = collapse;
  window.collapse2 = collapse2;
}).call(this);
